import { z } from 'zod';

// ============================================
// OFFER MANAGEMENT VALIDATORS
// ============================================

export const approveOfferSchema = z.object({});

export const presentOfferSchema = z.object({
  presentedAt: z.string().datetime().optional(),
});

export const flagOfferSchema = z.object({
  issueType: z.enum([
    'rate_below_market',
    'rate_above_budget',
    'hours_below_minimum',
    'start_date_too_soon',
    'missing_information',
    'other'
  ]),
  details: z.string().min(10, 'Flag details required (minimum 10 characters)'),
});

export const unflagOfferSchema = z.object({});

export const candidateResponseSchema = z.object({
  response: z.enum(['accepted', 'negotiating', 'declined']),
  counterRate: z.number().min(5, 'Counter rate must be at least $5').optional(),
  counterHours: z.number().min(20, 'Minimum 20 hours per week').max(60, 'Maximum 60 hours per week').optional(),
  counterMessage: z.string().optional(),
  declineReason: z.string().optional(),
  declineNotes: z.string().optional(),
});

// ============================================
// FINALIZATION: INVOICE & PAYMENT
// ============================================

export const generateInvoiceSchema = z.object({
  amount: z.number().positive('Invoice amount must be positive'),
  description: z.string().optional(),
  // invoiceNumber is auto-generated by backend
});

export const paymentReceivedSchema = z.object({
  transactionId: z.string().min(1, 'Transaction ID is required'),
  amount: z.number().positive('Payment amount must be positive').optional(), // Optional - already set during invoice generation
  method: z.enum(['bank_transfer', 'credit_card', 'stripe', 'other']),
  paidAt: z.string().datetime().optional(),
});

// ============================================
// FINALIZATION: CONTRACT
// ============================================

export const generateContractSchema = z.object({
  // contractId is auto-generated by backend
});

export const sendContractSchema = z.object({
  recipient: z.enum(['client', 'candidate']),
});

export const signContractSchema = z.object({
  signer: z.enum(['client', 'candidate']),
  signedAt: z.string().datetime().optional(),
});

// ============================================
// FINALIZATION: PAYROLL
// ============================================

export const setupPayrollSchema = z.object({
  partner: z.string().min(1, 'Payroll partner is required'),
  reference: z.string().optional(),
  bankDetailsCollected: z.boolean().optional(),
  scheduleConfigured: z.boolean().optional(),
  firstPayDate: z.string().datetime().optional(),
  notes: z.string().optional(),
});

// ============================================
// FINALIZATION: COMPLIANCE
// ============================================

export const verifyComplianceSchema = z.object({
  taxClassification: z.boolean(),
  laborRequirements: z.boolean(),
  privacyRequirements: z.boolean(),
  notes: z.string().optional(),
});

// ============================================
// FINALIZATION: CSM & START DATE
// ============================================

export const assignCsmSchema = z.object({
  name: z.string().min(1, 'CSM name is required'),
  email: z.string().email('Invalid email format').optional(),
  phone: z.string().optional(),
});

export const confirmStartDateSchema = z.object({
  candidateConfirmed: z.boolean(),
  clientConfirmed: z.boolean(),
  notes: z.string().optional(),
});

// ============================================
// NOTES
// ============================================

export const addNoteSchema = z.object({
  content: z.string().min(1, 'Note content is required'),
});

// ============================================
// TYPE EXPORTS
// ============================================

export type ApproveOfferInput = z.infer<typeof approveOfferSchema>;
export type PresentOfferInput = z.infer<typeof presentOfferSchema>;
export type FlagOfferInput = z.infer<typeof flagOfferSchema>;
export type UnflagOfferInput = z.infer<typeof unflagOfferSchema>;
export type CandidateResponseInput = z.infer<typeof candidateResponseSchema>;

export type GenerateInvoiceInput = z.infer<typeof generateInvoiceSchema>;
export type PaymentReceivedInput = z.infer<typeof paymentReceivedSchema>;

export type GenerateContractInput = z.infer<typeof generateContractSchema>;
export type SendContractInput = z.infer<typeof sendContractSchema>;
export type SignContractInput = z.infer<typeof signContractSchema>;

export type SetupPayrollInput = z.infer<typeof setupPayrollSchema>;
export type VerifyComplianceInput = z.infer<typeof verifyComplianceSchema>;

export type AssignCsmInput = z.infer<typeof assignCsmSchema>;
export type ConfirmStartDateInput = z.infer<typeof confirmStartDateSchema>;

export type AddNoteInput = z.infer<typeof addNoteSchema>;
